FIND_PATH(SQLITE3_INCLUDE_DIR NAMES sqlite3.h)

FIND_LIBRARY(SQLITE3_LIBRARY NAMES sqlite3)

SET(SQLITE3_LIBRARIES ${SQLITE3_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SQLITE3 DEFAULT_MSG SQLITE3_LIBRARY SQLITE3_LIBRARIES)

MARK_AS_ADVANCED(SQLITE3_LIBRARY SQLITE3_LIBRARIES)
